name: DAST Pipeline Golang API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_scan:
    name: Build and Start Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and Start containers
        run: |
          docker-compose up --build -d
          sleep 15  # esperamos que levante DB y API

      - name: Run OWASP ZAP scan inside container
        run: |
          docker exec zap-scanner zap-baseline.py -t http://api:9090 -r zap-report.html -f openapi -I || true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP Report
          path: zap-report.html

      - name: Stop and Clean containers
        run: docker-compose down
