name: DAST Pipeline Golang API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_scan:
    name: Build, Deploy and Run DAST
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DSN: ${{ secrets.DSN }}
      BINARY_NAME: ${{ secrets.BINARY_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and Start containers
        run: |
          docker-compose up --build -d
          echo "Waiting for API to be ready..."
          for i in $(seq 1 90); do
            if curl -s http://localhost:9090 > /dev/null; then
              echo "API is ready!"
              break
            fi
            echo "API not ready yet, waiting 1 second..."
            sleep 1
          done
          if ! curl -s http://localhost:9090 > /dev/null; then
            echo "API did not become ready in time. Exiting."
            echo "--- Logs del contenedor golang_api_sqli ---"
            docker logs golang_api_sqli
            exit 1
          fi

  sonarcloud_scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: build_and_scan # Asegura que este job se ejecute solo si 'build_and_scan' fue exitoso

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- NUEVO: Instalar docker-compose en este job también ---
      - name: Install docker-compose for clean-up
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
      # --- FIN NUEVO ---

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # --- MODIFICACIÓN CLAVE PARA SONARCLOUD ---
      - name: Run SonarCloud analysis
        uses: SonarSource/sonarqube-scan-action@v5.0.0 # Usar la acción recomendada
        # Ya NO se pasan inputs aquí, se usa sonar-project.properties y env
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Pasar el token como variable de entorno al paso
      # --- FIN MODIFICACIÓN ---

      - name: Stop and Clean containers
        if: always() # Esto asegura que siempre se intenten limpiar los contenedores
        run: docker-compose down -v --rmi all